runtime: java25
entrypoint: java -jar data-all.jar

env_variables:
  OTEL_JAVAAGENT_ENABLED: "false"
  OTEL_SDK_DISABLED: "true"

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
